# Generated by Django 6.0.7 on 2026-08-21 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tutorsession',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AddField(
            model_name='tutorsession',
            name='title',
            field=models.CharField(default='New Study Session', max_length=100),
        ),
    ]
