# Generated by Django 6.0.7 on 2026-08-27 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0002_alter_subject_unique_together_alter_subject_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='elective_group',
            field=models.CharField(blank=True, help_text='e.g. Elective-I, Elective-II', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='is_elective',
            field=models.BooleanField(default=False, help_text='True if this is an elective course'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='code',
            field=models.CharField(blank=True, help_text='e.g. CS401 or BCE6804', max_length=50, null=True),
        ),
    ]
